# -*- coding: utf-8 -*-
"""python2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehCLDp9zg_jMv4v-m7GzF3q2e6nNrSoU
"""

x= int(input('no1= '))
y= int(input('no2= '))
if x>y:
  print('greater value = ',x)
  print('smaller value = ',y)
else:
  print('greater value = ',y)
  print('smaller value = ',x)

x= int(input('no1= '))
y= int(input('no2= '))
z= int(input('no3= '))

if x>y and x>z:
  if y>z:
   print(f'{x} is greater')
   print(f'{z} is smaller')
  else:
   print(f'{x} is greater')
   print(f'{y} is smaller')

elif y>x and y>z:
 if x>z:
   print(f'{y} is greater')
   print(f'{z} is smaller')
 else:
   print(f'{y} is greater')
   print(f'{x} is smaller')

elif z>x and z>y:
 if x>y:
   print(f'{z} is greater')
   print(f'{y} is smaller')
 else:
   print(f'{z} is greater')
   print(f'{x} is smaller')

x = int(input('enter x: '))
if x%2 == 0:
  print('its even')
else:
  print('its odd')

x = int(input('enter x: '))
if x%10 == 0:
  print('its divisible')
else:
  print('its not divisible')

x = int(input('enter age: '))
if x>=18:
  print('Major')
elif x<18:
  print('Minor')

yr = int(input('enter year: '))
if yr%4 == 0:
  print('its a leap yr')
else:
  print('its not a leap yr')

a1 = int(input('enter angle1: '))
a2 = int(input('enter angle2: '))
a3 = int(input('enter angle3: '))
if a1+a2+a3 == 180:
  print('triangle valid')
else:
  print('triangle unvalid')

x = int(input('enter x: '))
if x>0:
  print(x)
elif x<0:
  print(-x)

l = int(input('enter length: '))
b = int(input('enter breadth: '))
A = l*b
P = 2*(l+b)
if A>P:
  print('area is more')
else:
  print('perimeter is more')

print('point 1:')
x1 = int(input('x1 = '))
y1 = int(input('y1 = '))

print('point 2:')
x2 = int(input('x2 = '))
y2 = int(input('y2 = '))

print('point 3:')
x3 = int(input('x3 = '))
y3 = int(input('y3 = '))

if 1/2*(x1*(y2-y3) + x2*(y3-y1) + x3*(y1-y2)) == 0:
  print('points are collinear')
else:
  print('points are not collinear')

print('center :')
x = int(input('x = '))
y = int(input('y = '))

print('point :')
x1 = int(input('x1 = '))
y1 = int(input('y1 = '))

r = int(input('radius: '))

if (x-x1)**2 + (y-y1)**2 == r**2:
  print('pt is on the circle')
elif (x-x1)**2 + (y-y1)**2 < r**2:
  print('pt lies inside circle')
elif (x-x1)**2 + (y-y1)**2 > r**2:
  print('pt lies outside circle')

def noName(n):
    words = [
        "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
        "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
        "seventeen", "eighteen", "nineteen"
    ]
    if 0 <= n <= 19:
        return words[n]
for i in range(20):
    print(f"{i}: {noName(i)}")

m1 = int(input('enter marks1: '))
m2 = int(input('enter marks2: '))
m3 = int(input('enter marks3: '))
tot = m1+m2+m3
print('total = ',tot)
avg = tot/3
print('average = ',avg)
if m1<=39: print('student 1: failed')
else: print('student 1 passed')
if m2<=39: print('student 2 failed')
else: print('student 2 passed')
if m3<=39: print('student 3 failed')
else: print('student 3 passed')